name: "New Issue"
description: "Report a bug, UI issue, or request an enhancement."
labels: []  # Labels will be selected based on the dropdown
projects:
  - "Computing-For-All/nextjs-issue-tracker"

body:
  - type: dropdown
    id: issue_type
    attributes:
      label: "Issue Type"
      description: "Select the type of issue you are reporting."
      options:
        - Bug
        - Content
        - Enhancement
    validations:
      required: true

  - type: textarea
    id: issue_description
    attributes:
      label: "Issue Description"
      description: "Provide a detailed description of the issue."
    validations:
      required: true

  - type: input
    id: issue_url
    attributes:
      label: "URL of the Page"
      description: "Provide the URL of the page where the issue is occurring."
      placeholder: "https://watechcoalition.org/page-with-issue"
    validations:
      required: true
      pattern: "https?://.*"  # Ensure the input is a valid URL

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: "Steps to Reproduce"
      description: "Provide steps to reproduce the issue if applicable."
      placeholder: "1. Go to the homepage\n2. Click on the 'Login' button\n3. Enter credentials and press submit"
    validations:
      required: false

  - type: textarea
    id: expected_behavior
    attributes:
      label: "Expected Behavior"
      description: "Describe the expected behavior or outcome."
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: "Additional Context"
      description: "Add any other context, screenshots, or information."
    validations:
      required: false

  - type: input
    id: screenshot
    attributes:
      label: "Screenshot (Optional)"
      description: "Upload a screenshot to provide more context."
      placeholder: "Drag and drop or paste the screenshot here."
    validations:
      required: false
