name: Move Issue to In Progress When Assigned

on:
  issues:
    types:
      - assigned

jobs:
  move_to_in_progress:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      repository-projects: write

    steps:
      - name: Update Project Item Status
        uses: kalgurn/update-project-beta-item-status@v0.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

          # The ID of the project in GitHub Projects (Beta)
          project: 'Computing-For-All/nextjs-issue-tracker'

          # The ID of the item to update (will use the current issue's ID)
          item-id: ${{ github.event.issue.node_id }}

          # The new status
          status: '🚧 In Progress'  # Make sure this status is exactly as it appears in your Project
