name: Update to In Progress on Assignment

on:
  issues:
    types:
      - assigned

jobs:
  set-status-in-progres:
    name: Move Assigned Issue to In-progress
    runs-on: ubuntu-latest

    steps:
      - name: Update Project Item Status
        uses: kalgurn/update-project-item-status@main
        with:
          project-url: https://github.com/orgs/Computing-For-All/projects/3

          # Use a Personal Access Token (PAT) stored in GitHub secrets
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}

          # Reference the item ID from the previous step output
          item-id: ${{ steps.addItem.outputs.itemId }}

          # Set the new status to "🚧 In Progress"
          status: "🚧 In Progress"  # Update with your exact status name in the Project
